savePrefix: ''
minimumReleaseAge: 0
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0
  vitest: 5.0.3
  vite-plus: 1.1.0
  '@vitest/browser-playwright': 5.0.3
  '@vitest/coverage-v8': 5.0.3
  '@vitest/ui': 5.0.3
overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
allowBuilds:
  esbuild: true
  lefthook: true
peerDependencyRules:
  allowAny:
    - vite
    - vitest
