catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
  solid-js: 2.0.0-rc.1
  "@solidjs/web": 2.0.0-rc.1
  "@solidjs/router": 2.0.0-next.17
  "@solidjs/vite-plugin": 3.0.0-next.31
  "@types/node": 26.2.0
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
