savePrefix: ''
minimumReleaseAge: 0
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vitest: 4.1.11
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
allowBuilds:
  esbuild: true
  lefthook: true
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
