// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/(base)";
      page: true;
      $component: FileRouteLazyRef<typeof import("../routes/(base)")>;
      $$route?: undefined;
    },
    {
      path: "/(base)/*404";
      page: true;
      $component: FileRouteLazyRef<typeof import("../routes/(base)/[...404]")>;
      $$route: FileRouteEagerRef<typeof import("../routes/(base)/[...404]")>;
    },
    {
      path: "/(base)/(home)/";
      page: true;
      $component: FileRouteLazyRef<typeof import("../routes/(base)/(home)/index")>;
      $$route: FileRouteEagerRef<typeof import("../routes/(base)/(home)/index")>;
    },
    {
      path: "/(seo)/llms.txt/";
      page: false;
      $GET: FileRouteLazyRef<typeof import("../routes/(seo)/llms.txt/index")>;
      $HEAD: FileRouteLazyRef<typeof import("../routes/(seo)/llms.txt/index")>;
      $$route?: undefined;
    },
    {
      path: "/(seo)/robots.txt/";
      page: false;
      $GET: FileRouteLazyRef<typeof import("../routes/(seo)/robots.txt/index")>;
      $HEAD: FileRouteLazyRef<typeof import("../routes/(seo)/robots.txt/index")>;
      $$route?: undefined;
    },
    {
      path: "/(seo)/sitemap.xml/";
      page: false;
      $GET: FileRouteLazyRef<typeof import("../routes/(seo)/sitemap.xml/index")>;
      $HEAD: FileRouteLazyRef<typeof import("../routes/(seo)/sitemap.xml/index")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/(base)";
      page: true;
      $component: FileRouteLazyRef<typeof import("../routes/(base)")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/*404";
          id: "/*404";
          page: true;
          $component: FileRouteLazyRef<typeof import("../routes/(base)/[...404]")>;
          $$route: FileRouteEagerRef<typeof import("../routes/(base)/[...404]")>;
          children?: undefined;
        },
        {
          path: "/";
          id: "/(home)/";
          page: true;
          $component: FileRouteLazyRef<typeof import("../routes/(base)/(home)/index")>;
          $$route: FileRouteEagerRef<typeof import("../routes/(base)/(home)/index")>;
          children?: undefined;
        }
      ];
    }
  ];
}
