import type { UserConfig } from 'vite-plus'

import backendPolicy, {
  RELATIVE_IMPORT_RESTRICTION
} from './backendPolicy/index.ts'

const TEST_FILES = [
  '**/*.test.ts',
  '**/*.test.tsx',
  '**/*.spec.ts',
  '**/*.spec.tsx',
  '**/test/**',
  '**/tests/**',
  '**/fixtures/**'
]

export const lint: NonNullable<UserConfig['lint']> = {
  ignorePatterns: ['public/**', 'src/assets/**', 'src/@types/routes.d.ts'],
  categories: {
    correctness: 'off',
    nursery: 'off',
    pedantic: 'off',
    perf: 'off',
    restriction: 'off',
    style: 'off',
    suspicious: 'off'
  },
  jsPlugins: [
    { name: 'project', specifier: './tooling/css-modules-plugin.ts' },
    { name: 'backend', specifier: './tooling/backendPolicy/plugin.ts' },
    {
      name: 'architecture',
      specifier: './tooling/architecturePolicy/index.ts'
    },
    { name: 'solid', specifier: 'eslint-plugin-solid' },
    { name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }
  ],
  options: {
    typeAware: true,
    typeCheck: true
  },
  overrides: [
    ...backendPolicy,
    {
      files: ['src/infra/server/**/index.ts'],
      rules: {
        'import/no-unassigned-import': ['error', { allow: ['server-only'] }]
      }
    },
    {
      files: [
        'src/tests/pages/BackendError/BackendError.e2e.test.ts',
        'src/tests/helpers/readSiteOrigin/index.ts'
      ],
      rules: { 'import/no-nodejs-modules': 'off' }
    },
    {
      files: ['src/**/*.test.{ts,tsx}', 'tooling/**/*.test.ts'],
      rules: { 'unicorn/filename-case': 'off' }
    },
    {
      // Assinaturas ditadas por terceiros: middleware do Nitro, callbacks de
      // teste e hooks de plugin não aceitam um objeto no lugar dos parâmetros.
      files: [
        'src/**/*.test.{ts,tsx}',
        'src/tests/**/*.{ts,tsx}',
        'src/middleware/index.ts',
        'tooling/**/*.ts',
        'vite.config.ts'
      ],
      rules: { 'eslint/max-params': 'off' }
    },
    {
      files: ['src/@types/icons.d.ts'],
      rules: {
        'import/unambiguous': 'off'
      }
    },
    {
      files: ['src/**/*.tsx'],
      rules: {
        'typescript/explicit-module-boundary-types': 'off'
      }
    },
    {
      files: [
        'src/@types/solid.d.ts',
        'src/@types/env.d.ts',
        'src/@types/router.d.ts'
      ],
      rules: {
        'import/no-unassigned-import': 'off',
        // Estas declarações ampliam interfaces de terceiros por declaration merging.
        'typescript/consistent-type-definitions': ['error', 'interface']
      }
    },
    {
      files: ['tooling/lint.ts'],
      rules: {
        'eslint/max-lines': 'off'
      }
    },
    {
      files: TEST_FILES,
      rules: {
        'eslint/no-empty': 'off',
        'vitest/require-hook': 'error'
      }
    },
    {
      files: ['**/*.{test,spec}.{ts,tsx}'],
      rules: {
        'typescript/no-floating-promises': 'off',
        'typescript/no-misused-promises': 'off'
      }
    },
    {
      files: ['**/*.{ts,tsx,mts,cts}'],
      rules: {
        'eslint/no-undef': 'off'
      }
    },
    {
      files: ['vite.config.ts', 'tooling/**/*.ts'],
      rules: {
        'import/no-nodejs-modules': 'off'
      }
    },
    {
      files: ['src/App.tsx', 'src/Document.tsx'],
      rules: {
        'unicorn/filename-case': 'off'
      }
    },
    {
      files: ['src/middleware/index.ts'],
      rules: {
        'node/callback-return': 'off'
      }
    }
  ],
  plugins: [
    'import',
    'jsx-a11y',
    'node',
    'oxc',
    'promise',
    'typescript',
    'unicorn',
    'vitest'
  ],
  rules: {
    'architecture/layer-imports': 'error',
    'project/css-modules-import': 'error',
    'project/css-filename': 'error',
    'project/test-filename': 'error',
    'eslint/accessor-pairs': 'error',
    'eslint/array-callback-return': 'error',
    'eslint/arrow-body-style': ['error', 'as-needed'],
    'eslint/block-scoped-var': 'error',
    'eslint/capitalized-comments': 'off',
    'eslint/class-methods-use-this': 'off',
    'eslint/complexity': ['error', { max: 20 }],
    'eslint/constructor-super': 'error',
    'eslint/curly': ['error', 'multi-line'],
    'eslint/default-case': 'off',
    'eslint/default-case-last': 'error',
    'eslint/default-param-last': 'error',
    'eslint/eqeqeq': ['error', 'always'],
    'eslint/for-direction': 'error',
    'eslint/func-name-matching': 'off',
    'eslint/func-names': ['error', 'always'],
    'eslint/func-style': 'off',
    'eslint/getter-return': 'error',
    'eslint/grouped-accessor-pairs': 'error',
    'eslint/guard-for-in': 'error',
    'eslint/id-denylist': 'off',
    'eslint/id-length': 'off',
    'eslint/id-match': 'off',
    'eslint/init-declarations': 'off',
    'eslint/logical-assignment-operators': [
      'error',
      'always',
      { enforceForIfStatements: true }
    ],
    'eslint/max-classes-per-file': 'off',
    'eslint/max-depth': ['error', { max: 4 }],
    'eslint/max-lines': [
      'warn',
      { max: 800, skipBlankLines: true, skipComments: true }
    ],
    'eslint/max-lines-per-function': [
      'warn',
      { max: 200, skipBlankLines: true, skipComments: true }
    ],
    'eslint/max-nested-callbacks': ['warn', { max: 3 }],
    'eslint/max-params': ['error', { max: 1 }],
    'eslint/max-statements': 'off',
    'eslint/new-cap': 'off',
    'eslint/no-alert': 'off',
    'eslint/no-array-constructor': 'error',
    'eslint/no-async-promise-executor': 'error',
    'eslint/no-await-in-loop': 'off',
    'eslint/no-bitwise': 'off',
    'eslint/no-caller': 'error',
    'eslint/no-case-declarations': 'error',
    'eslint/no-class-assign': 'error',
    'eslint/no-compare-neg-zero': 'error',
    'eslint/no-cond-assign': 'error',
    'eslint/no-console': ['warn', { allow: ['warn', 'error'] }],
    'eslint/no-const-assign': 'error',
    'eslint/no-constant-binary-expression': 'error',
    'eslint/no-constant-condition': 'error',
    'eslint/no-constructor-return': 'error',
    'eslint/no-continue': 'off',
    'eslint/no-control-regex': 'error',
    'eslint/no-debugger': 'error',
    'eslint/no-delete-var': 'error',
    'eslint/no-div-regex': 'error',
    'eslint/no-dupe-class-members': 'error',
    'eslint/no-dupe-else-if': 'error',
    'eslint/no-dupe-keys': 'error',
    'eslint/no-duplicate-case': 'error',
    'eslint/no-duplicate-imports': [
      'error',
      { allowSeparateTypeImports: false }
    ],
    'eslint/no-else-return': 'error',
    'eslint/no-empty': ['error', { allowEmptyCatch: false }],
    'eslint/no-empty-character-class': 'error',
    'eslint/no-empty-function': 'error',
    'eslint/no-empty-pattern': 'error',
    'eslint/no-empty-static-block': 'error',
    'eslint/no-eq-null': 'error',
    'eslint/no-eval': 'error',
    'eslint/no-ex-assign': 'error',
    'eslint/no-extend-native': 'error',
    'eslint/no-extra-bind': 'error',
    'eslint/no-extra-boolean-cast': 'error',
    'eslint/no-extra-label': 'error',
    'eslint/no-fallthrough': 'error',
    'eslint/no-func-assign': 'error',
    'eslint/no-global-assign': 'error',
    'eslint/no-implicit-coercion': 'error',
    'eslint/no-implicit-globals': 'error',
    'eslint/no-implied-eval': 'error',
    'eslint/no-import-assign': 'error',
    'eslint/no-inline-comments': 'error',
    'eslint/no-inner-declarations': 'error',
    'eslint/no-invalid-regexp': 'error',
    'eslint/no-irregular-whitespace': 'error',
    'eslint/no-iterator': 'error',
    'eslint/no-label-var': 'error',
    'eslint/no-labels': 'error',
    'eslint/no-lone-blocks': 'error',
    'eslint/no-lonely-if': 'error',
    'eslint/no-loop-func': 'error',
    'eslint/no-loss-of-precision': 'error',
    'eslint/no-magic-numbers': [
      'error',
      {
        ignore: [0, 1],
        ignoreNumericLiteralTypes: true,
        ignoreDefaultValues: true,
        ignoreArrayIndexes: true
      }
    ],
    'eslint/no-misleading-character-class': 'error',
    'eslint/no-multi-assign': 'error',
    'eslint/no-multi-str': 'error',
    'eslint/no-negated-condition': 'error',
    'eslint/no-nested-ternary': 'error',
    'eslint/no-new': 'error',
    'eslint/no-new-func': 'error',
    'eslint/no-new-native-nonconstructor': 'error',
    'eslint/no-new-wrappers': 'error',
    'eslint/no-nonoctal-decimal-escape': 'error',
    'eslint/no-obj-calls': 'error',
    'eslint/no-object-constructor': 'error',
    'eslint/no-param-reassign': 'error',
    'eslint/no-plusplus': 'error',
    'eslint/no-promise-executor-return': 'error',
    'eslint/no-proto': 'error',
    'eslint/no-prototype-builtins': 'error',
    'eslint/no-redeclare': 'error',
    'eslint/no-regex-spaces': 'error',
    'eslint/no-restricted-exports': 'error',
    'eslint/no-restricted-globals': 'error',
    'eslint/no-restricted-imports': [
      'error',
      {
        patterns: [RELATIVE_IMPORT_RESTRICTION]
      }
    ],
    'eslint/no-restricted-properties': 'error',
    'eslint/no-return-assign': 'error',
    'eslint/no-script-url': 'error',
    'eslint/no-self-assign': 'error',
    'eslint/no-self-compare': 'error',
    'eslint/no-sequences': 'error',
    'eslint/no-setter-return': 'error',
    'eslint/no-shadow': 'error',
    'eslint/no-shadow-restricted-names': 'error',
    'eslint/no-sparse-arrays': 'error',
    'eslint/no-template-curly-in-string': 'error',
    'eslint/no-this-before-super': 'error',
    'eslint/no-throw-literal': 'error',
    'eslint/no-unassigned-vars': 'error',
    'eslint/no-undef': 'error',
    'eslint/no-undefined': 'off',
    'eslint/no-underscore-dangle': 'error',
    'eslint/no-unexpected-multiline': 'error',
    'eslint/no-unmodified-loop-condition': 'error',
    'eslint/no-unneeded-ternary': 'error',
    'eslint/no-unreachable': 'error',
    'eslint/no-unreachable-loop': 'error',
    'eslint/no-unsafe-finally': 'error',
    'eslint/no-unsafe-negation': 'error',
    'eslint/no-unsafe-optional-chaining': 'error',
    'eslint/no-unused-expressions': 'error',
    'eslint/no-unused-labels': 'error',
    'eslint/no-unused-private-class-members': 'error',
    'eslint/no-unused-vars': 'error',
    'eslint/no-use-before-define': 'error',
    'eslint/no-useless-assignment': 'error',
    'eslint/no-useless-backreference': 'error',
    'eslint/no-useless-call': 'error',
    'eslint/no-useless-catch': 'error',
    'eslint/no-useless-computed-key': 'error',
    'eslint/no-useless-concat': 'error',
    'eslint/no-useless-constructor': 'error',
    'eslint/no-useless-escape': 'error',
    'eslint/no-useless-rename': 'error',
    'eslint/no-useless-return': 'error',
    'eslint/no-var': 'error',
    'eslint/no-void': 'off',
    'eslint/no-warning-comments': 'off',
    'eslint/no-with': 'error',
    'eslint/object-shorthand': 'error',
    'eslint/one-var': 'off',
    'eslint/operator-assignment': 'error',
    'eslint/prefer-arrow-callback': [
      'error',
      { allowNamedFunctions: true, allowUnboundThis: true }
    ],
    'eslint/prefer-const': 'error',
    'eslint/prefer-destructuring': 'error',
    'eslint/prefer-exponentiation-operator': 'error',
    'eslint/prefer-named-capture-group': 'error',
    'eslint/prefer-numeric-literals': 'error',
    'eslint/prefer-object-has-own': 'error',
    'eslint/prefer-object-spread': 'error',
    'eslint/prefer-promise-reject-errors': 'error',
    'eslint/prefer-regex-literals': 'error',
    'eslint/prefer-rest-params': 'error',
    'eslint/prefer-spread': 'error',
    'eslint/prefer-template': 'error',
    'eslint/preserve-caught-error': 'error',
    'eslint/radix': 'error',
    'eslint/require-await': 'off',
    'eslint/require-unicode-regexp': 'error',
    'eslint/require-yield': 'error',
    'eslint/sort-keys': 'off',
    'eslint/sort-vars': 'off',
    'eslint/symbol-description': 'error',
    'eslint/unicode-bom': 'error',
    'eslint/use-isnan': 'error',
    'eslint/valid-typeof': 'error',
    'eslint/vars-on-top': 'error',
    'eslint/yoda': 'error',
    'import/consistent-type-specifier-style': [
      'error',
      'prefer-top-level-if-only-type-imports'
    ],
    'import/default': 'error',
    'import/export': 'error',
    'import/exports-last': 'error',
    'import/extensions': ['error', 'ignorePackages'],
    'import/first': 'error',
    'import/group-exports': 'off',
    'import/max-dependencies': 'off',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/newline-after-import': 'error',
    'import/no-absolute-path': 'error',
    'import/no-amd': 'error',
    'import/no-anonymous-default-export': 'error',
    'import/no-commonjs': 'error',
    'import/no-cycle': 'error',
    'import/no-duplicates': ['error', { preferInline: true }],
    'import/no-dynamic-require': 'error',
    'import/no-empty-named-blocks': 'error',
    'import/no-mutable-exports': 'error',
    'import/no-named-as-default': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-named-default': 'error',
    'import/no-namespace': ['error', { ignore: ['valibot'] }],
    'import/no-nodejs-modules': 'error',
    'import/no-relative-parent-imports': 'off',
    'import/no-self-import': 'error',
    'import/no-unassigned-import': ['error', { allow: ['**/*.css'] }],
    'import/no-webpack-loader-syntax': 'error',
    'import/unambiguous': 'error',
    'jsx-a11y/alt-text': 'error',
    'jsx-a11y/anchor-ambiguous-text': 'error',
    'jsx-a11y/anchor-has-content': 'error',
    'jsx-a11y/anchor-is-valid': 'error',
    'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
    'jsx-a11y/aria-props': 'error',
    'jsx-a11y/aria-proptypes': 'error',
    'jsx-a11y/aria-role': 'error',
    'jsx-a11y/aria-unsupported-elements': 'error',
    'jsx-a11y/autocomplete-valid': 'error',
    'jsx-a11y/click-events-have-key-events': 'error',
    'jsx-a11y/control-has-associated-label': 'error',
    'jsx-a11y/heading-has-content': 'error',
    'jsx-a11y/html-has-lang': 'error',
    'jsx-a11y/iframe-has-title': 'error',
    'jsx-a11y/img-redundant-alt': 'error',
    'jsx-a11y/interactive-supports-focus': 'error',
    'jsx-a11y/label-has-associated-control': 'error',
    'jsx-a11y/lang': 'error',
    'jsx-a11y/media-has-caption': 'error',
    'jsx-a11y/mouse-events-have-key-events': 'error',
    'jsx-a11y/no-access-key': 'error',
    'jsx-a11y/no-aria-hidden-on-focusable': 'error',
    'jsx-a11y/no-autofocus': 'error',
    'jsx-a11y/no-distracting-elements': 'error',
    'jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
    'jsx-a11y/no-noninteractive-element-interactions': 'error',
    'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
    'jsx-a11y/no-noninteractive-tabindex': 'error',
    'jsx-a11y/no-redundant-roles': 'error',
    'jsx-a11y/no-static-element-interactions': 'error',
    'jsx-a11y/prefer-tag-over-role': 'error',
    'jsx-a11y/role-has-required-aria-props': 'error',
    'jsx-a11y/role-supports-aria-props': 'error',
    'jsx-a11y/scope': 'error',
    'jsx-a11y/tabindex-no-positive': 'error',
    'node/callback-return': 'error',
    'node/exports-style': 'error',
    'node/global-require': 'error',
    'node/handle-callback-err': 'error',
    'node/no-exports-assign': 'error',
    'node/no-mixed-requires': 'error',
    'node/no-new-require': 'error',
    'node/no-path-concat': 'error',
    'node/no-process-env': 'error',
    'node/no-sync': 'error',
    'oxc/approx-constant': 'error',
    'oxc/bad-array-method-on-arguments': 'error',
    'oxc/bad-bitwise-operator': 'error',
    'oxc/bad-char-at-comparison': 'error',
    'oxc/bad-comparison-sequence': 'error',
    'oxc/bad-match-all-arg': 'error',
    'oxc/bad-min-max-func': 'error',
    'oxc/bad-object-literal-comparison': 'error',
    'oxc/bad-replace-all-arg': 'error',
    'oxc/branches-sharing-code': 'error',
    'oxc/const-comparisons': 'error',
    'oxc/double-comparisons': 'error',
    'oxc/erasing-op': 'error',
    'oxc/misrefactored-assign-op': 'error',
    'oxc/missing-throw': 'error',
    'oxc/no-accumulating-spread': 'error',
    'oxc/no-async-endpoint-handlers': 'error',
    'oxc/no-barrel-file': 'error',
    'oxc/no-const-enum': 'error',
    'oxc/no-map-spread': 'error',
    'oxc/no-rest-spread-properties': 'off',
    'oxc/no-this-in-exported-function': 'error',
    'oxc/number-arg-out-of-range': 'error',
    'oxc/only-used-in-recursion': 'error',
    'oxc/uninvoked-array-callback': 'error',
    'promise/always-return': 'error',
    'promise/avoid-new': 'error',
    'promise/catch-or-return': [
      'error',
      { allowThen: true, allowFinally: true }
    ],
    'promise/no-callback-in-promise': 'error',
    'promise/no-multiple-resolved': 'error',
    'promise/no-nesting': 'error',
    'promise/no-new-statics': 'error',
    'promise/no-promise-in-callback': 'error',
    'promise/no-return-in-finally': 'error',
    'promise/no-return-wrap': 'error',
    'promise/param-names': 'error',
    'promise/prefer-await-to-callbacks': 'error',
    'promise/prefer-await-to-then': ['error', { strict: true }],
    'promise/prefer-catch': 'error',
    'promise/spec-only': 'error',
    'promise/valid-params': 'error',
    'solid/components-return-once': 'warn',
    'solid/event-handlers': 'error',
    'solid/imports': 'warn',
    'solid/jsx-no-duplicate-props': 'error',
    'solid/jsx-no-script-url': 'error',
    'solid/jsx-no-undef': ['error', { typescriptEnabled: true }],
    'solid/jsx-uses-vars': 'error',
    'solid/no-accessor-as-prop': 'error',
    'solid/no-array-handlers': 'off',
    'solid/no-boolean-enumerated-attribute': 'error',
    'solid/no-browser-globals-in-server-function': 'error',
    'solid/no-destructure': 'error',
    'solid/no-innerhtml': 'error',
    'solid/no-invalid-server-capture': 'error',
    'solid/no-module-scope-reactive-primitive': 'error',
    'solid/no-proxy-apis': 'off',
    'solid/no-react-deps': 'off',
    'solid/no-react-specific-props': 'error',
    'solid/no-restated-default-options': 'error',
    'solid/no-single-arg-create-effect': 'error',
    'solid/no-store-mutation-outside-setter': 'error',
    'solid/no-unknown-namespaces': 'error',
    'solid/no-unused-signal': 'error',
    'solid/no-write-in-pure-computation': 'error',
    'solid/prefer-classlist': 'off',
    'solid/prefer-for': 'error',
    'solid/prefer-onSettled-for-side-effects': 'warn',
    'solid/prefer-show': 'off',
    'solid/prefer-structured-class': 'error',
    'solid/reactivity': ['warn', { customReactiveFunctions: ['dynamic'] }],
    'solid/removed-api': 'error',
    'solid/require-async-server-function': 'error',
    'solid/self-closing-comp': 'warn',
    'solid/style-prop': 'warn',
    'solid/valid-use-server': 'error',
    'typescript/adjacent-overload-signatures': 'error',
    'typescript/array-type': 'error',
    'typescript/await-thenable': 'error',
    'typescript/ban-ts-comment': 'error',
    'typescript/ban-tslint-comment': 'error',
    'typescript/ban-types': 'error',
    'typescript/class-literal-property-style': 'error',
    'typescript/consistent-generic-constructors': 'error',
    'typescript/consistent-indexed-object-style': 'error',
    'typescript/consistent-return': 'error',
    'typescript/consistent-type-assertions': 'error',
    'typescript/consistent-type-definitions': ['error', 'type'],
    'typescript/consistent-type-exports': 'error',
    'typescript/consistent-type-imports': [
      'error',
      { prefer: 'type-imports', fixStyle: 'inline-type-imports' }
    ],
    'typescript/dot-notation': 'error',
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-member-accessibility': 'error',
    'typescript/explicit-module-boundary-types': 'error',
    'typescript/method-signature-style': 'error',
    'typescript/no-array-delete': 'error',
    'typescript/no-base-to-string': 'error',
    'typescript/no-confusing-non-null-assertion': 'error',
    'typescript/no-confusing-void-expression': [
      'error',
      { ignoreArrowShorthand: true }
    ],
    'typescript/no-deprecated': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-duplicate-type-constituents': 'error',
    'typescript/no-dynamic-delete': 'error',
    'typescript/no-empty-interface': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-extraneous-class': 'error',
    'typescript/no-floating-promises': 'error',
    'typescript/no-for-in-array': 'error',
    'typescript/no-implied-eval': 'error',
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-inferrable-types': 'error',
    'typescript/no-invalid-void-type': 'error',
    'typescript/no-meaningless-void-operator': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-misused-promises': [
      'error',
      { checksVoidReturn: { attributes: false } }
    ],
    'typescript/no-misused-spread': 'error',
    'typescript/no-mixed-enums': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-nullish-coalescing': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-redundant-type-constituents': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-restricted-types': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-boolean-literal-compare': 'error',
    'typescript/no-unnecessary-condition': 'error',
    'typescript/no-unnecessary-parameter-property-assignment': 'error',
    'typescript/no-unnecessary-qualifier': 'error',
    'typescript/no-unnecessary-template-expression': 'error',
    'typescript/no-unnecessary-type-arguments': 'error',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unnecessary-type-conversion': 'error',
    'typescript/no-unnecessary-type-parameters': 'error',
    'typescript/no-unsafe-argument': 'error',
    'typescript/no-unsafe-assignment': 'error',
    'typescript/no-unsafe-call': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-unsafe-member-access': 'error',
    'typescript/no-unsafe-return': 'error',
    'typescript/no-unsafe-type-assertion': 'error',
    'typescript/no-unsafe-unary-minus': 'error',
    'typescript/no-useless-default-assignment': 'error',
    'typescript/no-useless-empty-export': 'error',
    'typescript/no-var-requires': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/non-nullable-type-assertion-style': 'error',
    'typescript/only-throw-error': 'error',
    'typescript/parameter-properties': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-enum-initializers': 'error',
    'typescript/prefer-find': 'error',
    'typescript/prefer-for-of': 'error',
    'typescript/prefer-function-type': 'error',
    'typescript/prefer-includes': 'error',
    'typescript/prefer-literal-enum-member': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/prefer-nullish-coalescing': 'off',
    'typescript/prefer-optional-chain': 'error',
    'typescript/prefer-promise-reject-errors': 'error',
    'typescript/prefer-readonly': 'error',
    'typescript/prefer-readonly-parameter-types': 'off',
    'typescript/prefer-reduce-type-parameter': 'error',
    'typescript/prefer-regexp-exec': 'error',
    'typescript/prefer-return-this-type': 'error',
    'typescript/prefer-string-starts-ends-with': 'error',
    'typescript/prefer-ts-expect-error': 'error',
    'typescript/promise-function-async': 'off',
    'typescript/related-getter-setter-pairs': 'error',
    'typescript/require-array-sort-compare': 'error',
    'typescript/require-await': 'error',
    'typescript/restrict-plus-operands': 'error',
    'typescript/restrict-template-expressions': 'error',
    'typescript/return-await': 'error',
    'typescript/strict-boolean-expressions': 'off',
    'typescript/strict-void-return': 'off',
    'typescript/switch-exhaustiveness-check': 'error',
    'typescript/triple-slash-reference': 'error',
    'typescript/unbound-method': 'error',
    'typescript/unified-signatures': 'error',
    'typescript/use-unknown-in-catch-callback-variable': 'error',
    'unicorn/catch-error-name': 'error',
    'unicorn/consistent-assert': 'error',
    'unicorn/consistent-date-clone': 'error',
    'unicorn/consistent-empty-array-spread': 'error',
    'unicorn/consistent-existence-index-check': 'error',
    'unicorn/consistent-function-scoping': 'error',
    'unicorn/consistent-template-literal-escape': 'error',
    'unicorn/custom-error-definition': 'error',
    'unicorn/empty-brace-spaces': 'error',
    'unicorn/error-message': 'error',
    'unicorn/escape-case': 'error',
    'unicorn/explicit-length-check': 'error',
    'unicorn/explicit-timer-delay': 'error',
    'unicorn/filename-case': 'error',
    'unicorn/import-style': 'error',
    'unicorn/max-nested-calls': 'error',
    'unicorn/new-for-builtins': 'error',
    'unicorn/no-abusive-eslint-disable': 'error',
    'unicorn/no-accessor-recursion': 'error',
    'unicorn/no-anonymous-default-export': 'error',
    'unicorn/no-array-callback-reference': 'error',
    'unicorn/no-array-fill-with-reference-type': 'error',
    'unicorn/no-array-for-each': 'off',
    'unicorn/no-array-method-this-argument': 'error',
    'unicorn/no-array-reduce': 'error',
    'unicorn/no-array-reverse': 'error',
    'unicorn/no-array-sort': 'error',
    'unicorn/no-await-expression-member': 'error',
    'unicorn/no-await-in-promise-methods': 'error',
    'unicorn/no-confusing-array-with': 'error',
    'unicorn/no-console-spaces': 'error',
    'unicorn/no-document-cookie': 'error',
    'unicorn/no-empty-file': 'error',
    'unicorn/no-hex-escape': 'error',
    'unicorn/no-immediate-mutation': 'error',
    'unicorn/no-instanceof-array': 'error',
    'unicorn/no-instanceof-builtins': 'error',
    'unicorn/no-invalid-fetch-options': 'error',
    'unicorn/no-invalid-remove-event-listener': 'error',
    'unicorn/no-length-as-slice-end': 'error',
    'unicorn/no-lonely-if': 'error',
    'unicorn/no-magic-array-flat-depth': 'error',
    'unicorn/no-negated-condition': 'error',
    'unicorn/no-negation-in-equality-check': 'error',
    'unicorn/no-nested-ternary': 'error',
    'unicorn/no-new-array': 'error',
    'unicorn/no-new-buffer': 'error',
    'unicorn/no-null': 'off',
    'unicorn/no-object-as-default-parameter': 'error',
    'unicorn/no-process-exit': 'error',
    'unicorn/no-single-promise-in-promise-methods': 'error',
    'unicorn/no-static-only-class': 'error',
    'unicorn/no-thenable': 'error',
    'unicorn/no-this-assignment': 'error',
    'unicorn/no-typeof-undefined': 'error',
    'unicorn/no-unnecessary-array-flat-depth': 'error',
    'unicorn/no-unnecessary-array-splice-count': 'error',
    'unicorn/no-unnecessary-await': 'error',
    'unicorn/no-unnecessary-slice-end': 'error',
    'unicorn/no-unreadable-array-destructuring': 'error',
    'unicorn/no-unreadable-iife': 'error',
    'unicorn/no-useless-collection-argument': 'error',
    'unicorn/no-useless-error-capture-stack-trace': 'error',
    'unicorn/no-useless-fallback-in-spread': 'error',
    'unicorn/no-useless-iterator-to-array': 'error',
    'unicorn/no-useless-length-check': 'error',
    'unicorn/no-useless-promise-resolve-reject': 'error',
    'unicorn/no-useless-spread': 'error',
    'unicorn/no-useless-switch-case': 'error',
    'unicorn/no-useless-undefined': 'error',
    'unicorn/no-zero-fractions': 'error',
    'unicorn/number-literal-case': 'error',
    'unicorn/numeric-separators-style': 'error',
    'unicorn/prefer-add-event-listener': 'error',
    'unicorn/prefer-array-find': 'error',
    'unicorn/prefer-array-flat': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-array-index-of': 'error',
    'unicorn/prefer-array-some': 'error',
    'unicorn/prefer-at': 'error',
    'unicorn/prefer-bigint-literals': 'error',
    'unicorn/prefer-blob-reading-methods': 'error',
    'unicorn/prefer-class-fields': 'error',
    'unicorn/prefer-classlist-toggle': 'error',
    'unicorn/prefer-code-point': 'error',
    'unicorn/prefer-date-now': 'error',
    'unicorn/prefer-default-parameters': 'error',
    'unicorn/prefer-dom-node-append': 'error',
    'unicorn/prefer-dom-node-dataset': 'error',
    'unicorn/prefer-dom-node-remove': 'error',
    'unicorn/prefer-dom-node-text-content': 'error',
    'unicorn/prefer-event-target': 'error',
    'unicorn/prefer-export-from': 'error',
    'unicorn/prefer-global-this': 'error',
    'unicorn/prefer-import-meta-properties': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-keyboard-event-key': 'error',
    'unicorn/prefer-logical-operator-over-ternary': 'error',
    'unicorn/prefer-math-min-max': 'error',
    'unicorn/prefer-math-trunc': 'error',
    'unicorn/prefer-modern-dom-apis': 'error',
    'unicorn/prefer-modern-math-apis': 'error',
    'unicorn/prefer-module': 'error',
    'unicorn/prefer-native-coercion-functions': 'error',
    'unicorn/prefer-negative-index': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/prefer-number-coercion': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-object-from-entries': 'error',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-prototype-methods': 'error',
    'unicorn/prefer-query-selector': 'error',
    'unicorn/prefer-reflect-apply': 'error',
    'unicorn/prefer-regexp-test': 'error',
    'unicorn/prefer-response-static-json': 'error',
    'unicorn/prefer-set-has': 'error',
    'unicorn/prefer-set-size': 'error',
    'unicorn/prefer-single-call': 'error',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-string-raw': 'error',
    'unicorn/prefer-string-replace-all': 'error',
    'unicorn/prefer-string-slice': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/prefer-string-trim-start-end': 'error',
    'unicorn/prefer-structured-clone': 'error',
    'unicorn/prefer-ternary': 'error',
    'unicorn/prefer-top-level-await': 'error',
    'unicorn/prefer-type-error': 'error',
    'unicorn/relative-url-style': 'error',
    'unicorn/require-array-join-separator': 'error',
    'unicorn/require-module-attributes': 'error',
    'unicorn/require-module-specifiers': 'error',
    'unicorn/require-number-to-fixed-digits-argument': 'error',
    'unicorn/require-post-message-target-origin': 'error',
    'unicorn/switch-case-braces': 'error',
    'unicorn/switch-case-break-position': 'error',
    'unicorn/text-encoding-identifier-case': 'error',
    'unicorn/throw-new-error': 'error',
    'vite-plus/prefer-vite-plus-imports': 'error',
    'vitest/consistent-each-for': 'error',
    'vitest/consistent-test-filename': 'error',
    'vitest/consistent-test-it': ['error', { fn: 'it' }],
    'vitest/consistent-vitest-vi': 'error',
    'vitest/expect-expect': 'error',
    'vitest/hoisted-apis-on-top': 'error',
    'vitest/max-expects': 'error',
    'vitest/max-nested-describe': 'error',
    'vitest/no-alias-methods': 'error',
    'vitest/no-commented-out-tests': 'error',
    'vitest/no-conditional-expect': 'error',
    'vitest/no-conditional-in-test': 'off',
    'vitest/no-conditional-tests': 'error',
    'vitest/no-disabled-tests': 'error',
    'vitest/no-duplicate-hooks': 'error',
    'vitest/no-focused-tests': 'error',
    'vitest/no-identical-title': 'error',
    'vitest/no-import-node-test': 'error',
    'vitest/no-interpolation-in-snapshots': 'error',
    'vitest/no-large-snapshots': 'error',
    'vitest/no-mocks-import': 'error',
    'vitest/no-restricted-matchers': 'error',
    'vitest/no-restricted-vi-methods': 'error',
    'vitest/no-standalone-expect': 'error',
    'vitest/no-test-prefixes': 'error',
    'vitest/no-test-return-statement': 'error',
    'vitest/no-unneeded-async-expect-function': 'error',
    'vitest/padding-around-after-all-blocks': 'error',
    'vitest/padding-around-test-blocks': 'error',
    'vitest/prefer-called-exactly-once-with': 'error',
    // prefer-called-times contradiz esta regra: as duas juntas proibiriam as duas formas.
    'vitest/prefer-called-once': 'error',
    'vitest/prefer-called-with': 'error',
    'vitest/prefer-comparison-matcher': 'error',
    'vitest/prefer-describe-function-title': 'error',
    'vitest/prefer-each': 'error',
    'vitest/prefer-equality-matcher': 'error',
    'vitest/prefer-expect-assertions': 'off',
    'vitest/prefer-expect-resolves': 'error',
    'vitest/prefer-expect-type-of': 'error',
    'vitest/prefer-hooks-in-order': 'error',
    'vitest/prefer-hooks-on-top': 'error',
    'vitest/prefer-import-in-mock': 'error',
    'vitest/prefer-importing-vitest-globals': 'off',
    'vitest/prefer-lowercase-title': 'error',
    'vitest/prefer-mock-promise-shorthand': 'error',
    'vitest/prefer-mock-return-shorthand': 'error',
    'vitest/prefer-snapshot-hint': 'error',
    'vitest/prefer-spy-on': 'error',
    'vitest/prefer-strict-boolean-matchers': 'error',
    'vitest/prefer-strict-equal': 'error',
    'vitest/prefer-to-be': 'error',
    // prefer-to-be-falsy/truthy exigem o oposto de prefer-strict-boolean-matchers;
    // a comparação estrita prevalece.
    'vitest/prefer-to-be-falsy': 'off',
    'vitest/prefer-to-be-object': 'error',
    'vitest/prefer-to-be-truthy': 'off',
    'vitest/prefer-to-contain': 'error',
    'vitest/prefer-to-have-been-called-times': 'error',
    'vitest/prefer-to-have-length': 'error',
    'vitest/prefer-todo': 'error',
    'vitest/require-awaited-expect-poll': 'error',
    'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
    'vitest/require-mock-type-parameters': 'error',
    'vitest/require-test-timeout': 'off',
    'vitest/require-to-throw-message': 'error',
    'vitest/require-top-level-describe': 'error',
    'vitest/valid-describe-callback': 'error',
    'vitest/valid-expect': 'error',
    'vitest/valid-expect-in-promise': 'error',
    'vitest/valid-title': 'error',
    'vitest/warn-todo': 'error'
  },
  settings: {
    'jsx-a11y': {
      attributes: {
        for: ['htmlFor', 'for']
      }
    },
    solid: { version: 2 }
  }
}
