import type { UserConfig } from 'vite-plus'

const TEST_FILES = [
  '**/*.test.ts',
  '**/*.test.tsx',
  '**/*.spec.ts',
  '**/*.spec.tsx',
  '**/test/**',
  '**/tests/**',
  '**/fixtures/**'
]

export const lint: NonNullable<UserConfig['lint']> = {
  plugins: [
    'import',
    'jsx-a11y',
    'node',
    'oxc',
    'promise',
    'typescript',
    'unicorn',
    'vitest'
  ],
  jsPlugins: [
    { name: 'solid', specifier: 'eslint-plugin-solid' },
    { name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }
  ],
  categories: {
    correctness: 'off',
    nursery: 'off',
    pedantic: 'off',
    perf: 'off',
    restriction: 'off',
    style: 'off',
    suspicious: 'off'
  },
  settings: {
    solid: { version: 2 },
    'jsx-a11y': {
      attributes: {
        for: ['htmlFor', 'for']
      }
    }
  },
  options: {
    typeAware: true,
    typeCheck: true
  },
  rules: {
    'eslint/accessor-pairs': 'error',
    'eslint/array-callback-return': 'error',
    'eslint/block-scoped-var': 'error',
    'eslint/constructor-super': 'error',
    'eslint/default-case-last': 'error',
    'eslint/default-param-last': 'error',
    'eslint/for-direction': 'error',
    'eslint/getter-return': 'error',
    'eslint/grouped-accessor-pairs': 'error',
    'eslint/no-array-constructor': 'error',
    'eslint/no-async-promise-executor': 'error',
    'eslint/no-caller': 'error',
    'eslint/no-case-declarations': 'error',
    'eslint/no-class-assign': 'error',
    'eslint/no-compare-neg-zero': 'error',
    'eslint/no-cond-assign': 'error',
    'eslint/no-const-assign': 'error',
    'eslint/no-constant-binary-expression': 'error',
    'eslint/no-constant-condition': 'error',
    'eslint/no-constructor-return': 'error',
    'eslint/no-control-regex': 'error',
    'eslint/no-debugger': 'error',
    'eslint/no-delete-var': 'error',
    'eslint/no-div-regex': 'error',
    'eslint/no-dupe-class-members': 'error',
    'eslint/no-dupe-else-if': 'error',
    'eslint/no-dupe-keys': 'error',
    'eslint/no-duplicate-case': 'error',
    'eslint/no-else-return': 'error',
    'eslint/no-empty': ['error', { allowEmptyCatch: false }],
    'eslint/no-empty-character-class': 'error',
    'eslint/no-empty-pattern': 'error',
    'eslint/no-empty-static-block': 'error',
    'eslint/no-eval': 'error',
    'eslint/no-ex-assign': 'error',
    'eslint/no-extend-native': 'error',
    'eslint/no-extra-bind': 'error',
    'eslint/no-extra-boolean-cast': 'error',
    'eslint/no-extra-label': 'error',
    'eslint/no-fallthrough': 'error',
    'eslint/no-func-assign': 'error',
    'eslint/no-global-assign': 'error',
    'eslint/no-implicit-globals': 'error',
    'eslint/no-implied-eval': 'error',
    'eslint/no-import-assign': 'error',
    'eslint/no-invalid-regexp': 'error',
    'eslint/no-irregular-whitespace': 'error',
    'eslint/no-iterator': 'error',
    'eslint/no-label-var': 'error',
    'eslint/no-labels': 'error',
    'eslint/no-loss-of-precision': 'error',
    'eslint/no-misleading-character-class': 'error',
    'eslint/no-multi-assign': 'error',
    'eslint/no-multi-str': 'error',
    'eslint/no-nested-ternary': 'error',
    'eslint/no-new-func': 'error',
    'eslint/no-new-native-nonconstructor': 'error',
    'eslint/no-new-wrappers': 'error',
    'eslint/no-nonoctal-decimal-escape': 'error',
    'eslint/no-obj-calls': 'error',
    'eslint/no-object-constructor': 'error',
    'eslint/no-param-reassign': 'error',
    'eslint/no-proto': 'error',
    'eslint/no-prototype-builtins': 'error',
    'eslint/no-redeclare': 'error',
    'eslint/no-regex-spaces': 'error',
    'eslint/no-return-assign': 'error',
    'eslint/no-self-assign': 'error',
    'eslint/no-self-compare': 'error',
    'eslint/no-sequences': 'error',
    'eslint/no-setter-return': 'error',
    'eslint/no-shadow-restricted-names': 'error',
    'eslint/no-sparse-arrays': 'error',
    'eslint/no-this-before-super': 'error',
    'eslint/no-unassigned-vars': 'error',
    'eslint/no-unexpected-multiline': 'error',
    'eslint/no-unneeded-ternary': 'error',
    'eslint/no-unreachable': 'error',
    'eslint/no-unreachable-loop': 'error',
    'eslint/no-unsafe-finally': 'error',
    'eslint/no-unsafe-negation': 'error',
    'eslint/no-unsafe-optional-chaining': 'error',
    'eslint/no-unused-expressions': 'error',
    'eslint/no-unused-labels': 'error',
    'eslint/no-unused-private-class-members': 'error',
    'eslint/no-useless-backreference': 'error',
    'eslint/no-useless-call': 'error',
    'eslint/no-useless-catch': 'error',
    'eslint/no-useless-computed-key': 'error',
    'eslint/no-useless-concat': 'error',
    'eslint/no-useless-constructor': 'error',
    'eslint/no-useless-escape': 'error',
    'eslint/no-useless-rename': 'error',
    'eslint/no-var': 'error',
    'eslint/no-void': ['error', { allowAsStatement: true }],
    'eslint/no-warning-comments': 'error',
    'eslint/no-with': 'error',
    'eslint/operator-assignment': 'error',
    'eslint/prefer-exponentiation-operator': 'error',
    'eslint/prefer-numeric-literals': 'error',
    'eslint/prefer-object-has-own': 'error',
    'eslint/prefer-promise-reject-errors': 'error',
    'eslint/prefer-regex-literals': 'error',
    'eslint/prefer-rest-params': 'error',
    'eslint/prefer-spread': 'error',
    'eslint/radix': 'error',
    'eslint/require-yield': 'error',
    'eslint/symbol-description': 'error',
    'eslint/unicode-bom': 'error',
    'eslint/use-isnan': 'error',
    'eslint/valid-typeof': 'error',
    'eslint/yoda': 'error',
    'import/default': 'error',
    'import/export': 'error',
    'import/named': 'error',
    'import/namespace': 'error',
    'import/no-absolute-path': 'error',
    'import/no-amd': 'error',
    'import/no-cycle': 'error',
    'import/no-empty-named-blocks': 'error',
    'import/no-named-as-default-member': 'error',
    'import/no-named-default': 'error',
    'import/no-self-import': 'error',
    'import/no-webpack-loader-syntax': 'error',
    'jsx-a11y/alt-text': 'error',
    'jsx-a11y/anchor-ambiguous-text': 'error',
    'jsx-a11y/anchor-has-content': 'error',
    'jsx-a11y/anchor-is-valid': 'error',
    'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
    'jsx-a11y/aria-props': 'error',
    'jsx-a11y/aria-proptypes': 'error',
    'jsx-a11y/aria-role': 'error',
    'jsx-a11y/aria-unsupported-elements': 'error',
    'jsx-a11y/autocomplete-valid': 'error',
    'jsx-a11y/click-events-have-key-events': 'error',
    'jsx-a11y/control-has-associated-label': 'error',
    'jsx-a11y/heading-has-content': 'error',
    'jsx-a11y/html-has-lang': 'error',
    'jsx-a11y/iframe-has-title': 'error',
    'jsx-a11y/img-redundant-alt': 'error',
    'jsx-a11y/interactive-supports-focus': 'error',
    'jsx-a11y/label-has-associated-control': 'error',
    'jsx-a11y/lang': 'error',
    'jsx-a11y/media-has-caption': 'error',
    'jsx-a11y/mouse-events-have-key-events': 'error',
    'jsx-a11y/no-access-key': 'error',
    'jsx-a11y/no-aria-hidden-on-focusable': 'error',
    'jsx-a11y/no-distracting-elements': 'error',
    'jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
    'jsx-a11y/no-noninteractive-element-interactions': 'error',
    'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
    'jsx-a11y/no-noninteractive-tabindex': 'error',
    'jsx-a11y/no-redundant-roles': 'error',
    'jsx-a11y/no-static-element-interactions': 'error',
    'jsx-a11y/role-has-required-aria-props': 'error',
    'jsx-a11y/role-supports-aria-props': 'error',
    'jsx-a11y/scope': 'error',
    'jsx-a11y/tabindex-no-positive': 'error',
    'node/global-require': 'error',
    'node/handle-callback-err': 'error',
    'node/no-exports-assign': 'error',
    'node/no-mixed-requires': 'error',
    'node/no-new-require': 'error',
    'node/no-path-concat': 'error',
    'oxc/approx-constant': 'error',
    'oxc/bad-array-method-on-arguments': 'error',
    'oxc/bad-bitwise-operator': 'error',
    'oxc/bad-char-at-comparison': 'error',
    'oxc/bad-comparison-sequence': 'error',
    'oxc/bad-match-all-arg': 'error',
    'oxc/bad-min-max-func': 'error',
    'oxc/bad-object-literal-comparison': 'error',
    'oxc/bad-replace-all-arg': 'error',
    'oxc/const-comparisons': 'error',
    'oxc/double-comparisons': 'error',
    'oxc/erasing-op': 'error',
    'oxc/misrefactored-assign-op': 'error',
    'oxc/missing-throw': 'error',
    'oxc/no-accumulating-spread': 'error',
    'oxc/no-barrel-file': 'error',
    'oxc/no-const-enum': 'error',
    'oxc/no-this-in-exported-function': 'error',
    'oxc/number-arg-out-of-range': 'error',
    'oxc/only-used-in-recursion': 'error',
    'oxc/uninvoked-array-callback': 'error',
    'promise/catch-or-return': [
      'error',
      { allowThen: true, allowFinally: true }
    ],
    'promise/no-multiple-resolved': 'error',
    'promise/no-new-statics': 'error',
    'promise/no-return-in-finally': 'error',
    'promise/no-return-wrap': 'error',
    'promise/spec-only': 'error',
    'promise/valid-params': 'error',
    'solid/components-return-once': 'warn',
    'solid/event-handlers': 'error',
    'solid/imports': 'warn',
    'solid/jsx-no-duplicate-props': 'error',
    'solid/jsx-no-script-url': 'error',
    'solid/jsx-no-undef': ['error', { typescriptEnabled: true }],
    'solid/jsx-uses-vars': 'error',
    'solid/no-accessor-as-prop': 'error',
    'solid/no-array-handlers': 'off',
    'solid/no-browser-globals-in-server-function': 'error',
    'solid/no-destructure': 'error',
    'solid/no-innerhtml': 'error',
    'solid/no-invalid-server-capture': 'error',
    'solid/no-module-scope-reactive-primitive': 'error',
    'solid/no-proxy-apis': 'off',
    'solid/no-react-deps': 'off',
    'solid/no-react-specific-props': 'error',
    'solid/no-restated-default-options': 'error',
    'solid/no-single-arg-create-effect': 'error',
    'solid/no-unknown-namespaces': 'error',
    'solid/prefer-classlist': 'off',
    'solid/prefer-for': 'error',
    'solid/prefer-onSettled-for-side-effects': 'warn',
    'solid/prefer-show': 'off',
    'solid/prefer-structured-class': 'error',
    'solid/reactivity': 'warn',
    'solid/removed-api': 'error',
    'solid/require-async-server-function': 'error',
    'solid/self-closing-comp': 'warn',
    'solid/style-prop': 'warn',
    'solid/valid-use-server': 'error',
    'typescript/adjacent-overload-signatures': 'error',
    'typescript/ban-tslint-comment': 'error',
    'typescript/consistent-type-assertions': 'error',
    'typescript/consistent-type-definitions': 'error',
    'typescript/consistent-type-exports': 'error',
    'typescript/dot-notation': 'error',
    'typescript/no-array-delete': 'error',
    'typescript/no-confusing-non-null-assertion': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-duplicate-type-constituents': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-floating-promises': 'error',
    'typescript/no-for-in-array': 'error',
    'typescript/no-implied-eval': 'error',
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-meaningless-void-operator': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-misused-promises': 'error',
    'typescript/no-misused-spread': 'error',
    'typescript/no-mixed-enums': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-nullish-coalescing': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-parameter-property-assignment': 'error',
    'typescript/no-unnecessary-qualifier': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-unsafe-unary-minus': 'error',
    'typescript/no-useless-empty-export': 'error',
    'typescript/no-var-requires': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-enum-initializers': 'error',
    'typescript/prefer-find': 'error',
    'typescript/prefer-for-of': 'error',
    'typescript/prefer-literal-enum-member': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/prefer-reduce-type-parameter': 'error',
    'typescript/prefer-ts-expect-error': 'error',
    'typescript/related-getter-setter-pairs': 'error',
    'typescript/restrict-plus-operands': 'error',
    'typescript/triple-slash-reference': 'error',
    'unicorn/consistent-empty-array-spread': 'error',
    'unicorn/consistent-template-literal-escape': 'error',
    'unicorn/error-message': 'error',
    'unicorn/explicit-timer-delay': 'error',
    'unicorn/no-accessor-recursion': 'error',
    'unicorn/no-anonymous-default-export': 'error',
    'unicorn/no-array-fill-with-reference-type': 'error',
    'unicorn/no-await-in-promise-methods': 'error',
    'unicorn/no-confusing-array-with': 'error',
    'unicorn/no-console-spaces': 'error',
    'unicorn/no-document-cookie': 'error',
    'unicorn/no-empty-file': 'error',
    'unicorn/no-instanceof-array': 'error',
    'unicorn/no-instanceof-builtins': 'error',
    'unicorn/no-invalid-fetch-options': 'error',
    'unicorn/no-invalid-remove-event-listener': 'error',
    'unicorn/no-length-as-slice-end': 'error',
    'unicorn/no-lonely-if': 'error',
    'unicorn/no-magic-array-flat-depth': 'error',
    'unicorn/no-negation-in-equality-check': 'error',
    'unicorn/no-new-buffer': 'error',
    'unicorn/no-single-promise-in-promise-methods': 'error',
    'unicorn/no-static-only-class': 'error',
    'unicorn/no-thenable': 'error',
    'unicorn/no-this-assignment': 'error',
    'unicorn/no-unnecessary-array-flat-depth': 'error',
    'unicorn/no-unnecessary-await': 'error',
    'unicorn/no-unnecessary-slice-end': 'error',
    'unicorn/no-unreadable-array-destructuring': 'error',
    'unicorn/no-unreadable-iife': 'error',
    'unicorn/no-useless-error-capture-stack-trace': 'error',
    'unicorn/no-useless-iterator-to-array': 'error',
    'unicorn/no-useless-length-check': 'error',
    'unicorn/no-useless-switch-case': 'error',
    'unicorn/prefer-array-flat': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-array-index-of': 'error',
    'unicorn/prefer-array-some': 'error',
    'unicorn/prefer-bigint-literals': 'error',
    'unicorn/prefer-blob-reading-methods': 'error',
    'unicorn/prefer-classlist-toggle': 'error',
    'unicorn/prefer-date-now': 'error',
    'unicorn/prefer-includes': 'error',
    'unicorn/prefer-keyboard-event-key': 'error',
    'unicorn/prefer-math-min-max': 'error',
    'unicorn/prefer-modern-dom-apis': 'error',
    'unicorn/prefer-negative-index': 'error',
    'unicorn/prefer-number-properties': 'error',
    'unicorn/prefer-object-from-entries': 'error',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-prototype-methods': 'error',
    'unicorn/prefer-reflect-apply': 'error',
    'unicorn/prefer-regexp-test': 'error',
    'unicorn/prefer-set-size': 'error',
    'unicorn/prefer-string-starts-ends-with': 'error',
    'unicorn/prefer-string-trim-start-end': 'error',
    'unicorn/prefer-structured-clone': 'error',
    'unicorn/require-array-join-separator': 'error',
    'unicorn/require-module-attributes': 'error',
    'unicorn/require-module-specifiers': 'error',
    'unicorn/require-number-to-fixed-digits-argument': 'error',
    'unicorn/switch-case-break-position': 'error',
    'unicorn/throw-new-error': 'error',
    'vite-plus/prefer-vite-plus-imports': 'error',
    'vitest/consistent-each-for': 'error',
    'vitest/hoisted-apis-on-top': 'error',
    'vitest/max-nested-describe': 'error',
    'vitest/no-commented-out-tests': 'error',
    'vitest/no-conditional-tests': 'error',
    'vitest/no-disabled-tests': 'error',
    'vitest/no-duplicate-hooks': 'error',
    'vitest/no-focused-tests': 'error',
    'vitest/no-identical-title': 'error',
    'vitest/no-interpolation-in-snapshots': 'error',
    'vitest/no-mocks-import': 'error',
    'vitest/no-standalone-expect': 'error',
    'vitest/no-test-prefixes': 'error',
    'vitest/no-test-return-statement': 'error',
    'vitest/no-unneeded-async-expect-function': 'error',
    'vitest/prefer-hooks-in-order': 'error',
    'vitest/prefer-hooks-on-top': 'error',
    'vitest/prefer-snapshot-hint': 'error',
    'vitest/prefer-to-be-object': 'error',
    'vitest/prefer-to-have-been-called-times': 'error',
    'vitest/prefer-todo': 'error',
    'vitest/require-awaited-expect-poll': 'error',
    'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
    'vitest/valid-describe-callback': 'error',
    'vitest/valid-expect-in-promise': 'error',
    'vitest/warn-todo': 'error'
  },
  overrides: [
    {
      files: TEST_FILES,
      rules: {
        'eslint/no-empty': 'off',
        'typescript/no-floating-promises': 'off',
        'typescript/no-misused-promises': 'off'
      }
    }
  ]
}
